apiVersion: v1
kind: Service
metadata:
    name: nodejsdemo-app
spec:
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 80 
      targetPort: 3000 
    selector:
        app: nodejsdemo-app